"""creating models for job research

Revision ID: 01c55defb38c
Revises: 366a4ac9c669
Create Date: 2025-08-10 08:46:41.724654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01c55defb38c'
down_revision: Union[str, Sequence[str], None] = '366a4ac9c669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('skills', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
