"""creating models for job 

Revision ID: 0a54b6f0d1a3
Revises: 8c6b9945615a
Create Date: 2025-08-10 09:58:03.929323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a54b6f0d1a3'
down_revision: Union[str, Sequence[str], None] = '8c6b9945615a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
