"""follow up mail sending feature

Revision ID: 1434dd88ba22
Revises: e61145996b3b
Create Date: 2025-08-10 15:30:46.646051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1434dd88ba22'
down_revision: Union[str, Sequence[str], None] = 'e61145996b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobapplications', sa.Column('last_reminder_sent', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobapplications', 'last_reminder_sent')
    # ### end Alembic commands ###
