"""added provider column in user table

Revision ID: 77411f62087f
Revises: 7e7b9b9a480f
Create Date: 2025-07-20 08:56:33.594041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77411f62087f'
down_revision: Union[str, Sequence[str], None] = '7e7b9b9a480f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

auth_provider_enum = sa.Enum('email', 'google', 'github', name='authprovider')

def upgrade() -> None:
    """Upgrade schema."""
    auth_provider_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_provider', auth_provider_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_provider')
    auth_provider_enum.drop(op.get_bind())
    # ### end Alembic commands ###
