"""creating models for job 

Revision ID: 8c6b9945615a
Revises: 91be4fde937c
Create Date: 2025-08-10 09:40:17.313283

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c6b9945615a'
down_revision: Union[str, Sequence[str], None] = '91be4fde937c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usercompanyresearch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mission', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vision', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('values', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('culture', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recent_news', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('competitors', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ceo_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('services', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_members', sa.Integer(), nullable=True),
    sa.Column('expected_salary_range', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hr_contact_names', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userjobresearch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_research_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detailed_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('required_skills', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tech_stack', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('team_structure', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('challenges', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['company_research_id'], ['usercompanyresearch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobapplications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_research_id', sa.Integer(), nullable=False),
    sa.Column('application_date', sa.DateTime(), nullable=False),
    sa.Column('resume_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['job_research_id'], ['userjobresearch.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobapplications')
    op.drop_table('userjobresearch')
    op.drop_table('usercompanyresearch')
    # ### end Alembic commands ###
