"""added provider column in user table

Revision ID: cc4e71966d39
Revises: 7e7b9b9a480f
Create Date: 2025-07-20 08:45:54.271991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc4e71966d39'
down_revision: Union[str, Sequence[str], None] = '7e7b9b9a480f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('auth_provider', sa.Enum('email', 'google', 'github', name='authprovider'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('users', 'auth_provider')
    # ### end Alembic commands ###
